#############################################################################
# Makefile for building: guard-puppy
# Generated by qmake (2.01a) (Qt 4.8.0) on: Wed Jan 25 11:20:49 2012
# Project:  guard-puppy.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.0/bin/qmake -o Makefile guard-puppy.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++-64 -I. -I/usr/local/Trolltech/Qt-4.8.0/include/QtCore -I/usr/local/Trolltech/Qt-4.8.0/include/QtGui -I/usr/local/Trolltech/Qt-4.8.0/include/QtXml -I/usr/local/Trolltech/Qt-4.8.0/include -I. -Isrc -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.0/lib /usr/lib/libboost_regex.so.1.46.1 -lQtXml -L/usr/local/Trolltech/Qt-4.8.0/lib -lQtGui -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/guarddogAboutDialog_w.cpp \
		src/guarddogDialog_w.cpp \
		src/myGuardDog.cpp moc_guarddogAboutDialog_w.cpp \
		moc_guarddogDialog_w.cpp
OBJECTS       = guarddogAboutDialog_w.o \
		guarddogDialog_w.o \
		myGuardDog.o \
		moc_guarddogAboutDialog_w.o \
		moc_guarddogDialog_w.o
DIST          = /usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf \
		guard-puppy.pro
QMAKE_TARGET  = guard-puppy
DESTDIR       = 
TARGET        = guard-puppy

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_AboutDialog.h ui_guarddog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: guard-puppy.pro  /usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtXml.prl \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtGui.prl
	$(QMAKE) -o Makefile guard-puppy.pro
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtXml.prl:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile guard-puppy.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/guard-puppy1.0.0 || $(MKDIR) .tmp/guard-puppy1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/guard-puppy1.0.0/ && $(COPY_FILE) --parents src/guarddogAboutDialog_w.h src/guarddogDialog_w.h .tmp/guard-puppy1.0.0/ && $(COPY_FILE) --parents src/guarddogAboutDialog_w.cpp src/guarddogDialog_w.cpp src/myGuardDog.cpp .tmp/guard-puppy1.0.0/ && $(COPY_FILE) --parents src/AboutDialog.ui src/guarddog.ui .tmp/guard-puppy1.0.0/ && (cd `dirname .tmp/guard-puppy1.0.0` && $(TAR) guard-puppy1.0.0.tar guard-puppy1.0.0 && $(COMPRESS) guard-puppy1.0.0.tar) && $(MOVE) `dirname .tmp/guard-puppy1.0.0`/guard-puppy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/guard-puppy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_guarddogAboutDialog_w.cpp moc_guarddogDialog_w.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_guarddogAboutDialog_w.cpp moc_guarddogDialog_w.cpp
moc_guarddogAboutDialog_w.cpp: ui_AboutDialog.h \
		src/guarddogAboutDialog_w.h
	/usr/local/Trolltech/Qt-4.8.0/bin/moc $(DEFINES) $(INCPATH) src/guarddogAboutDialog_w.h -o moc_guarddogAboutDialog_w.cpp

moc_guarddogDialog_w.cpp: ui_guarddog.h \
		src/guardDogFirewall.h \
		src/guarddogdoc.h \
		src/protocoldb.h \
		src/userdefinedprotocol.h \
		src/iprange.h \
		src/zone.h \
		src/guarddogDialog_w.h
	/usr/local/Trolltech/Qt-4.8.0/bin/moc $(DEFINES) $(INCPATH) src/guarddogDialog_w.h -o moc_guarddogDialog_w.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_AboutDialog.h ui_guarddog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_AboutDialog.h ui_guarddog.h
ui_AboutDialog.h: src/AboutDialog.ui
	/usr/local/Trolltech/Qt-4.8.0/bin/uic src/AboutDialog.ui -o ui_AboutDialog.h

ui_guarddog.h: src/guarddog.ui
	/usr/local/Trolltech/Qt-4.8.0/bin/uic src/guarddog.ui -o ui_guarddog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

guarddogAboutDialog_w.o: src/guarddogAboutDialog_w.cpp src/guarddogAboutDialog_w.h \
		ui_AboutDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guarddogAboutDialog_w.o src/guarddogAboutDialog_w.cpp

guarddogDialog_w.o: src/guarddogDialog_w.cpp src/guarddogDialog_w.h \
		ui_guarddog.h \
		src/guardDogFirewall.h \
		src/guarddogdoc.h \
		src/protocoldb.h \
		src/userdefinedprotocol.h \
		src/iprange.h \
		src/zone.h \
		src/guarddogAboutDialog_w.h \
		ui_AboutDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guarddogDialog_w.o src/guarddogDialog_w.cpp

myGuardDog.o: src/myGuardDog.cpp src/guarddogDialog_w.h \
		ui_guarddog.h \
		src/guardDogFirewall.h \
		src/guarddogdoc.h \
		src/protocoldb.h \
		src/userdefinedprotocol.h \
		src/iprange.h \
		src/zone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myGuardDog.o src/myGuardDog.cpp

moc_guarddogAboutDialog_w.o: moc_guarddogAboutDialog_w.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guarddogAboutDialog_w.o moc_guarddogAboutDialog_w.cpp

moc_guarddogDialog_w.o: moc_guarddogDialog_w.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guarddogDialog_w.o moc_guarddogDialog_w.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

